name = "WeightedCVT"
uuid = "770ca0ce-b1ea-490c-93de-6aee52022c72"
authors = ["Mikhail Khrenov <mkhrenov34@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BenchmarkTools = "1.5.0"
CUDA = "5.5.2"
GLMakie = "0.10.16"
GeometryBasics = "0.4.11"
LinearAlgebra = "1.11.0"
Meshing = "0.7.0"
Profile = "1.11.0"
SparseArrays = "1.11.0"
StaticArrays = "1.9.8"
